// @generated by `cargo run --bin harvest_quants` — do not edit by hand.
//! Per-repo GGUF quant variants. Regenerate with `cargo run --bin harvest_quants`.
use crate::catalog::QuantVariant;

pub static QUANT_VARIANTS: &[(&str, &[QuantVariant])] = &[];
